version: "3.9"

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "7000:7000"
    volumes:
      - ./auth:/auth
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: app-network